'use client';
import { FormEvent,useState } from 'react';
type Asset={id:string;name:string;slug:string};
type Lookup={name?:string;latitude?:number;longitude?:number;url?:string};

export default function AdminForms({assets,canEdit}:{assets:Asset[];canEdit:boolean}){
  const[status,setStatus]=useState('');const[lookup,setLookup]=useState<Lookup>({});const[mapUrl,setMapUrl]=useState('');const[looking,setLooking]=useState(false);
  async function submit(url:string,body:BodyInit){setStatus('Saving…');const response=await fetch(url,{method:'POST',body});const result=await response.json();setStatus(response.ok?'Saved.':result.error||'Unable to save.')}
  async function resolveMap(){if(!mapUrl)return;setLooking(true);setStatus('Reading the Google Maps link…');const response=await fetch('/api/places/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:mapUrl})});const result=await response.json();setLookup(result);setStatus(response.ok?'Place found. Check the details, then save it.':result.error||'Unable to read that link.');setLooking(false)}
  if(!canEdit)return <div className="notice"><strong>You have view-only access.</strong><p>An administrator must promote your profile to editor before you can add content.</p></div>;
  return <><div className="admin-tabs"><article className="admin-panel"><h2>Upload a manual</h2><p>PDF, text, or Markdown; up to 50 MB.</p><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();submit('/api/documents',new FormData(e.currentTarget))}}><label>Title<input name="title" required placeholder="Webasto heating manual"/></label><label>For<select name="asset_id"><option value="">General</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Document<input name="file" type="file" accept=".pdf,.txt,.md" required/></label><label><input name="is_published" type="checkbox" defaultChecked/> Publish for visitors</label><button>Upload and index</button></form></article><article className="admin-panel"><h2>Save a place</h2><p>Paste a Google Maps sharing link. No paid Google API is used.</p><label>Google Maps link<input type="url" value={mapUrl} onChange={e=>setMapUrl(e.target.value)} placeholder="https://maps.app.goo.gl/…"/></label><button type="button" onClick={resolveMap} disabled={!mapUrl||looking}>{looking?'Finding place…':'Find place'}</button><form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();submit('/api/places',new FormData(e.currentTarget))}}><input type="hidden" name="google_maps_url" value={lookup.url||mapUrl}/><label>Name<input name="name" required key={lookup.name} defaultValue={lookup.name||''} placeholder="The Riverside Arms"/></label><label>Category<select name="category"><option value="mooring">Mooring</option><option value="pub">Pub</option><option value="cafe">Café</option><option value="shop">Shop</option><option value="fuel">Fuel</option><option value="other">Other</option></select></label><div className="form-row"><label>Latitude<input name="latitude" type="number" step="any" required key={`lat-${lookup.latitude}`} defaultValue={lookup.latitude}/></label><label>Longitude<input name="longitude" type="number" step="any" required key={`lng-${lookup.longitude}`} defaultValue={lookup.longitude}/></label></div><label>Our photograph (optional)<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/heic"/></label><label>Notes<textarea name="notes" rows={4}/></label><button>Save place</button></form></article></div><p className="save-status" role="status" aria-live="polite">{status}</p></>}
