// Generated from the Environment Agency guidance "River Thames: distances and
// measurements for boaters" (gov.uk, retrieved 31 August 2026). Ordered from
// Cricklade Bridge downstream to Teddington; kmToNext/minutesToNext describe
// the reach to the next entry downstream, cruising at the 8 km/h limit.
export const THAMES_LOCKS = [
  { name: 'Cricklade Bridge', kmToNext: 18.88, minutesToNext: 142 },
  { name: 'St John’s Lock', kmToNext: 1.85, minutesToNext: 15 },
  { name: 'Buscot Lock', kmToNext: 5.37, minutesToNext: 41 },
  { name: 'Grafton Lock', kmToNext: 2.98, minutesToNext: 23 },
  { name: 'Radcot Lock', kmToNext: 4.23, minutesToNext: 32 },
  { name: 'Rushey Lock', kmToNext: 6.92, minutesToNext: 52 },
  { name: 'Shifford Lock', kmToNext: 7.63, minutesToNext: 58 },
  { name: 'Northmoor Lock', kmToNext: 6.21, minutesToNext: 47 },
  { name: 'Pinkhill Lock', kmToNext: 2.38, minutesToNext: 18 },
  { name: 'Eynsham Lock', kmToNext: 4.37, minutesToNext: 33 },
  { name: 'Kings Lock', kmToNext: 1.81, minutesToNext: 14 },
  { name: 'Godstow Lock', kmToNext: 3.87, minutesToNext: 30 },
  { name: 'Osney Lock', kmToNext: 3.73, minutesToNext: 28 },
  { name: 'Iffley Lock', kmToNext: 2.70, minutesToNext: 21 },
  { name: 'Sandford Lock', kmToNext: 7.38, minutesToNext: 56 },
  { name: 'Abingdon Lock', kmToNext: 4.15, minutesToNext: 32 },
  { name: 'Culham Lock', kmToNext: 4.52, minutesToNext: 34 },
  { name: 'Clifton Lock', kmToNext: 4.80, minutesToNext: 36 },
  { name: 'Days Lock', kmToNext: 6.37, minutesToNext: 48 },
  { name: 'Benson Lock', kmToNext: 10.46, minutesToNext: 79 },
  { name: 'Cleeve Lock', kmToNext: 1.00, minutesToNext: 8 },
  { name: 'Goring Lock', kmToNext: 6.55, minutesToNext: 50 },
  { name: 'Whitchurch Lock', kmToNext: 3.67, minutesToNext: 28 },
  { name: 'Mapledurham Lock', kmToNext: 7.08, minutesToNext: 54 },
  { name: 'Caversham Lock', kmToNext: 4.23, minutesToNext: 32 },
  { name: 'Sonning Lock', kmToNext: 4.68, minutesToNext: 36 },
  { name: 'Shiplake Lock', kmToNext: 4.80, minutesToNext: 36 },
  { name: 'Marsh Lock', kmToNext: 4.59, minutesToNext: 35 },
  { name: 'Hambleden Lock', kmToNext: 5.89, minutesToNext: 45 },
  { name: 'Hurley Lock', kmToNext: 1.03, minutesToNext: 8 },
  { name: 'Temple Lock', kmToNext: 2.70, minutesToNext: 22 },
  { name: 'Marlow Lock', kmToNext: 6.44, minutesToNext: 49 },
  { name: 'Cookham Lock', kmToNext: 3.35, minutesToNext: 26 },
  { name: 'Boulters Lock', kmToNext: 3.43, minutesToNext: 26 },
  { name: 'Bray Lock', kmToNext: 5.10, minutesToNext: 39 },
  { name: 'Boveney Lock', kmToNext: 3.75, minutesToNext: 29 },
  { name: 'Romney Lock', kmToNext: 4.83, minutesToNext: 37 },
  { name: 'Old Windsor Lock', kmToNext: 4.70, minutesToNext: 36 },
  { name: 'Bell Weir Lock', kmToNext: 4.57, minutesToNext: 35 },
  { name: 'Penton Hook Lock', kmToNext: 3.13, minutesToNext: 24 },
  { name: 'Chertsey Lock', kmToNext: 3.32, minutesToNext: 25 },
  { name: 'Shepperton Lock', kmToNext: 4.75, minutesToNext: 36 },
  { name: 'Sunbury Lock', kmToNext: 4.79, minutesToNext: 36 },
  { name: 'Molesey Lock', kmToNext: 7.74, minutesToNext: 59 },
  { name: 'Teddington Lock (to Teddington Boundary Obelisk)', kmToNext: 0.39, minutesToNext: 3 },
] as const;
